# Welcome to Jekyll!
#
title: Spectral
description: |
  BSc + MSc in Informatics Engineering and Computing
  Faculdade de Engenharia da Universidade do Porto
  crafted by [HTML5 UP](http://html5up.net)
owner: Diogo Marques
first_published: 2017
email: marques999@gmail.com
baseurl: ""
url: "https://marques999.github.io"
social:
  twitter: https://twitter.com/xmarques999
  github: https://github.com/marques999
  linkedin-square: https://linkedin.com/in/diogo-marques-a98290130/
  facebook-official: https://facebook.com/marques999
  google-plus-square: https://plus.google.com/u/0/114006488892497372994
  #email: /contact/
  #spotify:
  #stack-overflow:
  #vimeo:
  #reddit:
  #deviantart:
  #stackexchange:
  #trello:
  #bitbucket-square:
  #slack:
  #yelp:
  #leanpub:
  #connectdevelop:
  #ils:

markdown: kramdown