title: Diogo Marques
description: 'BSc + MSc in Informatics and Computer Engineering'
url: 'https://marques999.github.io'
baseurl: '/'
google_analytics: 'UA-107396044-1'
disqus_shortname: 'diogo-marques'

author:
  name: 'Diogo Marques'
  email: marques999@gmail.com
  twitter_username: xmarques999
  facebook_username: marques999
  github_username:  marques999
  linkedin_username:  diogo-marques-a98290130

defaults:
  -
    scope:
      path: ''
      type: 'posts'
    values:
        layout: 'post'

destination: _site
paginate: 10
permalink: /:year/:title/
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

gems: ['jekyll-paginate']
exclude: ['README.md', 'Gemfile', 'Gemfile.lock', 'screenshot.png']
